---
title: "COPE data for NYU Langone cohort: behavior restrictions"
author: "Michelle.VanTieghem"
date: "June 1, 2020"
output:
  html_document:
    number_sections: no
    df_print: paged
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      
---
# README
note: only including participants who fully completed baseline survey.


```{r, echo = F, message = F, warning = F, include = F}
knitr::opts_chunk$set( message = F, warning = F)


# load packages
library(tidyverse)
library(ggplot2)
library(readxl)


# load custom packages
source(paste0(data_dir, "custom_functions.R"))
#data_dir = paste0(data_dir, ""
baseline_clean2 <- read.csv(paste0(data_dir, "clean_data/cleaned_baseline_survey_2020-07-14.csv"))
```


# Restrictions
```{r}

restrict_table <- baseline_clean2 %>%
  group_by(status, first_child) %>%
  summarize(N_total = n(),
            'In-person contact with member of household' = sum(covid_behavior_restrictions___1),
            'In-person contact with family not in household' = sum(covid_behavior_restrictions___2),
            'In-person contact with friends' = sum(covid_behavior_restrictions___3),
            'In person contact with other parents' = sum(covid_behavior_restrictions___4),
            'In-person contact with work colleagues' = sum(covid_behavior_restrictions___5), 
            'In-person events in the community' = sum(covid_behavior_restrictions___12), 
            'In-person religious events' = sum(covid_behavior_restrictions___13),
            'Regular childcare by outside care provider' = sum(covid_behavior_restrictions___6), 
            'Cancellation of family or personal travel' = sum(covid_behavior_restrictions___7), 
            'Family activities in outdoor spaces' = sum(covid_behavior_restrictions___8), 
            'Family activities in public spaces' = sum(covid_behavior_restrictions___9),
            'Going to restaurants or stores' = sum(covid_behavior_restrictions___10), 
            'Exercise or recreational' = sum(covid_behavior_restrictions___11))
```

table by status & first_child
```{r}
restrict_table_long <- restrict_table %>%
  gather(key = "Restrictions", value = "N_endorsed", -N_total, -status, -first_child) %>%
  mutate(Percent = round((N_endorsed/N_total)*100, 2)) %>%
  select(status, first_child, Restrictions,  N_endorsed, Percent)
restrict_table_long

write.csv(restrict_table_long, file = paste0(data_dir, "tables/covid_behavior_restrictions_by_4groups.csv"), row.names = F)
```

plot restrictions
```{r,  echo = F}
restrictions_plot <- restrict_table_long %>%
    mutate(Restrictions = reorder(Restrictions, Percent)) %>%
ggplot( aes(x = Restrictions, y = Percent, fill = first_child)) + 
  geom_bar(stat =  "identity", position = position_dodge()) + 
   coord_flip()  + xlab("") + ylim(0, 100) + facet_grid(~status) +
    ylab ("Percent") +  custom_theme + my_colors_fill + 
  labs(#title = "Behavior restrictions due to the Covid-19 pandemic", 
     fill = "First Child",
    caption = paste("Data aggregated from", sum(restrict_table$N_total), 
                    "new and expecting mothers")) 

restrictions_plot 
#ggsave(restrictions_plot, file = paste0(data_dir, "plots/covid_restrictions_by_status.png")
```

# activities people miss the most
table and plot across all groups 
```{r}
N_total <- nrow(baseline_clean2 %>% filter(!is.na(activities_miss_most)))
miss_table <- baseline_clean2 %>%
    filter(!is.na(activities_miss_most)) %>%
  mutate(activities_miss_most = ifelse(grepl("person", activities_miss_most), 
                                       "In-person contact", as.character(activities_miss_most))) %>%
group_by(activities_miss_most) %>%
  count() %>% ungroup() %>%
    mutate(Percent = round((n/N_total)*100, 2)) 


miss_impact_plot <- miss_table %>%
    mutate(activities_miss_most = reorder(activities_miss_most, Percent)) %>%
  ggplot( aes(x = activities_miss_most, y = Percent)) + 
  geom_bar(stat =  "identity", position = position_dodge(), fill = "navy") +
   coord_flip()  + theme_bw() + xlab("") + ylim(0, 100) +
    ylab ("Percent") +  custom_theme + my_colors_fill + 
  labs(#title = "Which activities do women miss the most?", 
       caption = paste("Data aggregated from", N_total, "new and expecting mothers"))
miss_impact_plot 

#ggsave(miss_impact_plot, file = paste0(data_dir, "plots/activities_miss_most_by_status.png")
```

## missed activities by group 
```{r}
miss_table_by_group <- baseline_clean2 %>%
    filter(!is.na(activities_miss_most)) %>%
  mutate(activities_miss_most = ifelse(grepl("person", activities_miss_most), 
                                       "In-person contact", as.character(activities_miss_most))) %>%
  group_by(status, first_child) %>%
  summarize(N_total = n(), 
            "In-person contact" = sum(ifelse(activities_miss_most == "In-person contact", 1, 0), na.rm = T),
            "Going to restaurants or stores" = sum(ifelse(grepl("restaurants", activities_miss_most), 1, 0), na.rm = T),
            "Cancellation of family or personal travel" = sum(ifelse(grepl("travel", activities_miss_most), 1, 0), na.rm = T),
            "Family activites in public spaces" = sum(ifelse(activities_miss_most == "Family activities in public spaces", 1, 0), na.rm = T),
            "Childcare" = sum(ifelse(grepl("childcare", activities_miss_most), 1, 0), na.rm = T),
              "Exercise/recreations" = sum(ifelse(grepl("xercise", activities_miss_most), 1, 0), na.rm = T))


miss_table_long <- miss_table_by_group %>%
   gather(key = "activity_miss_most", value = "N_endorsed", -N_total, -status, -first_child) %>%
  mutate(Percent = round((N_endorsed/N_total)*100, 2)) 

miss_table_long
write.csv(miss_table_long, file = paste0(data_dir, "tables/activity_miss_most_by_4groups.csv"), row.names = F)

```


## facts
```{r}

miss_most <- miss_table %>%
  filter(Percent == max(Percent)) %>%
  mutate(Percent = round(Percent)) 

miss_most$Percent
```
