---
title: "COPE EDA: impact & disruption"
author: "Michelle.VanTieghem"
date: "June 24, 2020"
output:
  html_document:
    number_sections: no
    df_print: kable
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---


```{r, echo = F, message = F, warning = F, include = F}
knitr::opts_chunk$set(message = F, warning = F)

library(psych)
# load packages
library(corrplot)
library(tidyverse)
library(ggplot2)
library(readxl)

data_dir <- "../"
# load custom packages
source(paste0(data_dir, "custom_functions.R"))

baseline_df <- read.csv(paste0(data_dir, "clean_data/cleaned_baseline_survey_2020-07-14.csv"))

```

get relevant demo data 
```{r}
disrupt_df <- baseline_df %>%
   # making categorical
  mutate(currently_pregnant = as.factor(currently_pregnant), 
         treatment_any_past___1 = as.factor(treatment_any_past___1),
         treatment_mh_current___1 = as.factor(treatment_mh_current___1))
```

### material concern variables
0	Not of concern \
1	Mildly distressing \
2	Moderately distressing \
3	Highly distressing \

```{r}

concern_long <- disrupt_df %>%
  select(contains("concern"), status, median_income) %>%
  rename("Food or goods" = concern_food, 
         "Medicine" = concern_medicine, 
         "Baby supplies" = concern_babysupplies, 
         "Mental health care" = concern_mh, 
         "Health care" = concern_health_care,
         "Social interactions" = concern_social) %>%
  gather(key = "Concern", value = "Rating", -status, -median_income )

concern_long_table <- concern_long %>%
  filter(!is.na(Concern)) %>%
  group_by(status, Concern) %>%
  summarize(N_total = n(), 
            mean_rating = mean(Rating, na.rm = T), 
            upper_rating = mean_rating + sd(Rating, na.rm = T),
            lower_rating = mean_rating - sd(Rating, na.rm = T))

N_total <- concern_long_table$N_total[concern_long_table$status == "New Mom"] +
  concern_long_table$N_total[concern_long_table$status == "Pregnant"]

list_concerns <- unique(concern_long_table$Concern)

# plot ratings from lowest to highest
concern_plot <- concern_long_table %>%
  mutate(Concern = fct_reorder(Concern, mean_rating)) %>%
#  filter(Concern %in% choice_concerns) %>%
  ggplot(aes(x = Concern, y = mean_rating, fill = status)) +  
    geom_bar(stat =  "identity", position = position_dodge()) + 
    theme_bw() + xlab("") + ylab("Concern Rating (mean)") +
      custom_theme + my_colors_fill + ylim(0, 3) + coord_flip() +
  labs("", subtitle = "",
         caption ="0 = no concern, 3 = very concerned \n",
         paste("Data aggregated from", N_total, "new and expecting mothers"))

#Concerned about future access to...
concern_plot
#ggsave(concern_plot, file= "../plots/concern_ratings_by_preg_status.png")

```

### Distress variables

```{r}
covid_distress_long <- disrupt_df %>%
  select( covid_family_distress, covid_self_distress, status) %>%
  rename("Covid illness: family" = covid_family_distress, 
         "Covid illness: self" = covid_self_distress) %>%
  gather(key = "Distress", value = "Rating", -status) %>%
  mutate(Distress = str_remove(Distress, "_distress"))


covid_distress_long_table <- covid_distress_long %>%
  filter(!is.na(Distress)) %>%
  group_by(status, Distress) %>%
  summarize(N_total = n(), 
            mean_rating = mean(Rating, na.rm = T), 
            upper_rating = mean_rating + sd(Rating, na.rm = T),
            lower_rating = mean_rating - sd(Rating, na.rm = T))

N_total <- covid_distress_long_table$N_total[covid_distress_long_table$status == "New Mom"] +
  covid_distress_long_table$N_total[covid_distress_long_table$status == "Pregnant"]

# plot ratings from lowest to highest
covid_distress_plot <- covid_distress_long_table %>%
  ggplot(aes(x = Distress, y = mean_rating, fill = status)) + 
    geom_bar(stat =  "identity", position = position_dodge()) + 
    theme_bw() + xlab("") + ylab("Mean Distress Rating") +
      custom_theme + my_colors_fill + ylim(0, 6) + 
 labs(title = "Distress about potential covid-19 illness", 
         subtitle = "0 = no distress, 6 = extremely distressed",
       caption = paste("Data aggregated from", N_total, "new and expecting mothers"))

covid_distress_plot
#ggsave(covid_distress_plot, file= "../plots/covid_distress_ratings_by_preg_status.png", width = 9, height = 5)
```


### Disrupt variables
```{r}
# removing healthy meals, belongs in another category.
disrupt_long <- disrupt_df %>%
  select(contains("disrupted"), status, - disrupted_meal_rating) %>%
  rename("work activities" = disrupted_work_rating, 
         "social activities" = disrupted_social_activities_rating, 
         "physical activities" = disrupted_physical_rating) %>%
  gather(key = "disrupt", value = "Rating", -status) 


disrupt_long_table <- disrupt_long %>%
  filter(!is.na(disrupt)) %>%
  group_by(status, disrupt) %>%
  summarize(N_total = n(), 
            mean_rating = mean(Rating, na.rm = T), 
            upper_rating = mean_rating + sd(Rating, na.rm = T),
            lower_rating = mean_rating - sd(Rating, na.rm = T))
N_total <- disrupt_long_table$N_total[disrupt_long_table$status == "New Mom"] +
  disrupt_long_table$N_total[disrupt_long_table$status == "Pregnant"]

# plot ratings from lowest to highest
disrupt_plot <- disrupt_long_table %>%
  mutate(disrupt = fct_reorder(disrupt, mean_rating)) %>%
  ggplot(aes(x = disrupt, y = mean_rating, fill = status)) +  
    geom_bar(stat =  "identity", position = position_dodge()) + 
    theme_bw() + xlab("") + ylab("Mean Disruption Rating") + 
      custom_theme + my_colors_fill + ylim(0, 6) + coord_flip() +
  labs(title = "Disruptions due to the Covid-19 pandemic", 
         caption = " (0 = none, 6 = extreme disruption)")
        #  caption = paste("Data aggregated from", N_total, "new and expecting mothers"))
# how much has the COVID-19 outbreak disrupted your ability to engage in..

disrupt_plot
#ggsave(disrupt_plot, file= "../plots/disrupt_ratings_by_preg_status.png", width = 9, height = 5)
```


## covid valence impact

```{r}

impact_table <- disrupt_df %>% 
  select(record_id, impact_covid_valence, status) %>%
  mutate(valence = ifelse(impact_covid_valence> 0, "positive",
                          ifelse(impact_covid_valence == 0, "neutral", "negative"))) %>%
    filter(!is.na(valence)) %>%
  group_by(status, valence) %>%
  summarize(N_endorsed = n()) %>%
  mutate(N_total = NA)

N_preg <- impact_table %>% filter(status == "Pregnant") %>%
  summarize(N_total = sum(N_endorsed))
N_new_mom <- impact_table %>% filter(status == "New Mom") %>%
  summarize(N_total = sum(N_endorsed))
N_total <- N_preg$N_total + N_new_mom$N_total

impact_table_long <- impact_table %>%
  mutate(N_total = ifelse(status == "New Mom", N_new_mom$N_total, N_preg$N_total),
           percent = round((N_endorsed/N_total)*100))

valence_plot <- impact_table_long %>%
   mutate(valence = fct_reorder(valence, percent)) %>%
  ggplot(aes(x = valence, y = percent, fill = status)) + coord_flip()  +
  geom_bar(stat = "identity", position = position_dodge()) + 
  theme_bw() + xlab ("") + 
  ylab("Percent") +custom_theme + my_colors_fill + my_colors_color +
  labs(title = "Has covid-19 had a positive or negative impact on your life?", 
          caption = paste("Data aggregated from", N_total, "new and expecting mothers"))

valence_plot

#ggsave(valence_plot, file= "../plots/valence_impact_on_life_by_preg_status.png")
```



## General impact of covid
```{r}
impact <- baseline_df %>%
  select(status, impact_covid_rating, stress_covid_rating) %>%
  # put on scale so 0 = no stress or no impact.
  mutate(impact_covid_rating = impact_covid_rating -1, 
         stress_covid_rating = stress_covid_rating -1)

impact_long <- impact %>%
  gather(key = "measure", value = "Rating", 
         impact_covid_rating, stress_covid_rating, -status) %>%
  mutate(measure = ifelse(measure == "impact_covid_rating", 
                          "Daily Impact", "Stress Level"))

impact_long_table <- impact_long %>%
  group_by(status, measure) %>%
  summarize(mean_rating = mean(Rating, na.rm = T), 
            upper_rating = mean_rating + sd(Rating, na.rm = T),
            lower_rating = mean_rating - sd(Rating, na.rm = T))

# plot ratings from lowest to highest
impact_plot <- impact_long_table %>%
  ggplot(aes(x = measure, y = mean_rating, fill = status)) +  
    geom_bar(stat =  "identity", position = position_dodge()) + 
    theme_bw() + xlab("") + ylab("Mean Rating") +
    custom_theme + my_colors_fill + ylim(0, 6) +
     ggtitle("Self-reported Rating", subtitle = "0 = nothing, 6 = extreme")

impact_plot
#ggsave(impact_plot, file= "../plots/impact_stress_ratings_by_preg_status.png")
```

## biggest stressor
```{r}
greatest_stress <- baseline_df %>%
  select(status, source_stress_covid) %>%
  filter(!is.na(source_stress_covid)) %>%
  mutate(source_stress = as.factor(ifelse(source_stress_covid == 1, "Health concerns",ifelse(source_stress_covid == 2, "Financial concerns", ifelse(source_stress_covid == 3, "Impact on your child", ifelse(source_stress_covid == 4, "Impact on your partner", ifelse(source_stress_covid == 5, "Impact on your community", ifelse(source_stress_covid == 6, "Impact on family members", ifelse(source_stress_covid == 7, "Impact on close friends", ifelse(source_stress_covid == 8, "Impact on society", ifelse(source_stress_covid == 9, "Access to food", ifelse(source_stress_covid == 10, "Access to baby supplies", ifelse(source_stress_covid == 11, "Access to mental health care", ifelse(source_stress_covid == 12, "Social distancing", ifelse(source_stress_covid == 13, "Other", "Not stressed")))))))))))))))

N_preg <- greatest_stress %>% filter(status == "Pregnant") %>% count()
N_newmom <- greatest_stress %>% filter(status == "New Mom") %>% count()
N_total <- N_preg + N_newmom

stress_table <- greatest_stress %>%
  group_by(status, source_stress) %>%
  summarize(N_endorsed = n())
stress_table <- stress_table %>%
  mutate(N_total = ifelse(status == "New Mom", N_newmom$n, N_preg$n), 
         percent = round((N_endorsed/N_total)*100)) %>%
   filter(source_stress != "Not stressed" & 
          percent > 1 & source_stress != "Other" & 
           source_stress != "Access to food" & 
           source_stress != "Access to baby supplies" & 
           source_stress != "Impact on society")


# plot ratings from lowest to highest
stress_plot <- stress_table %>%
    mutate(source_stress = fct_reorder(source_stress, percent)) %>%
  ggplot(aes(x = source_stress, y = percent, fill = status)) +  
    geom_bar(stat =  "identity", position = position_dodge()) + 
    theme_bw() + ylab("Percent") + xlab("") + coord_flip() + 
      custom_theme + my_colors_fill + 
  labs(#title = "Single greatest source of stress due to Covid-19", 
          caption = paste("Data aggregated from", N_total, "new and expecting mothers"))
stress_plot

#ggsave(stress_plot, file= "../plots/single_greatest_stress_by_preg_status.png")
```
