---
title: "COPE: data cleaning_impact_disruption_vars"
author: "Michelle.VanTieghem"
date: "June 24, 2020"
output:
  html_document:
    number_sections: no
    df_print: kable
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---



```{r, message = F, warning = F, include = F, echo = F}
knitr::opts_chunk$set(message = F, warning = F)

library(psych)
# load packages
library(corrplot)
library(tidyverse)
library(ggplot2)
library(readxl)


```

```{r}
# load cleaned data
load("../cope_data_dashboard/clean_data/baseline_deidentified_df.Rdata")
# fix names of variables
baseline_clean3 <- baseline_clean2 %>%
  rename(covid_family_distress = covid_family_distreess,
         preg_birth_concern_rating = preg_supp_concern_rating_2,
         social_disruptions_distress = social_disruptions_rating)
```


#  cleaning data 
## likert scale Qs
```{r}

# get concern vars that eveyrone answered.
concern_vars_all <- names(baseline_clean3)[grepl("concern", names(baseline_clean3))]
concern_vars <-  concern_vars_all[!grepl("mom", concern_vars_all) & 
                                         !grepl("preg", concern_vars_all)]

# mom and preg vars will be used later...
distress_vars <- names(baseline_clean3)[grepl("stress", names(baseline_clean3)) & 
                                           !grepl("birth", names(baseline_clean3))]

disrupt_vars <- names(baseline_clean3)[grepl("disrupt", names(baseline_clean3))]

rating_vars <- baseline_clean3 %>%
  select(status, all_of(concern_vars), all_of(distress_vars), 
         all_of(disrupt_vars),  record_id) %>%
  # remove open ended questions that we don't want to include here.
  select(-contains("describe"), -contains("reduct"), -change_stress_rating) %>%
  # For all ratings 1 = no concern / distress, 7 = highest concern/ distress.
  # so we want to make everything 0-6 instead of 1-7 
  mutate_if(is.numeric, funs (. -1)) %>%
# make a version that futher removes columsn we don't want, and removes NAs.
  select(-"other_great_source_stress", -source_stress_covid) %>%
  drop_na() 

nrow(rating_vars)
```

##  valence questions
```{r}
change_vars <- names(baseline_clean3)[grepl("change_", names(baseline_clean3)) &
                                        grepl("_rating", names(baseline_clean3))]

valence_vars <- baseline_clean3 %>%
  select(change_stress_rating, change_sleep_rating, change_energy_rating, impact_covid_valence, record_id) %>%
  # mean center these variables, because 1 = worsened and 5 = improved 
  # now -2 = worsened and +2 = improved 
  mutate_if(is.numeric, funs(. -3)) %>%
  drop_na()

# this scoring was not in the same order, so needs to be hand-coded.
home_change <- baseline_clean3 %>%
  select(home_change, home_change_rating, record_id) %>%
  # if they didn't say their living environment changed, code as zero.
  mutate(home_change_rating = ifelse(home_change == 0, 0,
             # if they did say it changed, record their answer.
           ifelse(home_change_rating == 1, 2,
                    ifelse(home_change_rating == 2, 1, 
                               ifelse(home_change_rating == 3, -1,
                               ifelse(home_change_rating == 4, -2, 
                                      ifelse(home_change_rating == 5, 0, NA))))))) %>%
  drop_na() %>% select(-home_change)

nrow(home_change)
```

## combine all the data
```{r}
pred_vars <- home_change %>%
  left_join(., valence_vars, by = "record_id") %>%
  left_join(., rating_vars, by = "record_id") %>%
  drop_na()

pred_vars_no_labels <- pred_vars %>%
  select(-record_id)
nrow(pred_vars)

```


## save relevant data 
```{r}
save(pred_vars, pred_vars_no_labels,  file = "../cope_data_dashboard/clean_data/impact_disruption_cleaned.Rda")
```
